menu/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.menu_list, name='menu_list'),
    url(r'^menu/(?P<pk>\d+)/edit/$', views.create_new_or_edit_menu, name='menu_edit'),
    url(r'^menu/item/new/$', views.create_new_item, name="new_item"),
    url(r'^menu/(?P<pk>\d+)/', views.menu_detail, name='menu_detail'),
    url(r'^menu/item/(?P<pk>\d+)/$', views.item_detail, name='item_detail'),
    url(r'^menu/new/$', views.create_new_or_edit_menu, name='menu_new'),
    url(r'^menu/item/(?P<pk>\d+)/edit/$', views.edit_item, name="item_edit")
]

mysite/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('menu.urls', namespace='menu')),
]

urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url('^__debug__/', include(debug_toolbar.urls)),
    ]

menu/models.py
from datetime import date

from django.core.urlresolvers import reverse
from django.db import models


class Menu(models.Model):
    season = models.CharField(max_length=20)
    items = models.ManyToManyField('Item')
    created_date = models.DateField(
            default=date.today
    )
    expiration_date = models.DateField(
            blank=True, null=True)

    class Meta:
        ordering = ['expiration_date',]

    def __str__(self):
        return self.season

    def get_absolute_url(self):
        return reverse(
            'menu:menu_detail',
            kwargs={
                'pk': self.pk
            }
        )


class Item(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    chef = models.ForeignKey('auth.User')
    created_date = models.DateField(
            default=date.today)
    standard = models.BooleanField(default=False)
    ingredients = models.ManyToManyField('Ingredient', related_name='ingredients')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse(
            'menu:item_detail',
            kwargs={
                'pk': self.pk
            }
        )


class Ingredient(models.Model):
    name = models.CharField(max_length=200, unique=True)

    def __str__(self):
        return self.name

menu/forms.py
from datetime import date

from django import forms
from django.forms.extras.widgets import SelectDateWidget


from .models import Menu, Item


def must_expire_in_the_future(expire):
    if expire <= date.today():
        raise forms.ValidationError(
            "Menu expiration date must be in the future"
        )


class MenuForm(forms.ModelForm):

    class Meta:
        model = Menu
        fields = (
            'season',
            'expiration_date',
            'items'
        )
        widgets = {
            'expiration_date': SelectDateWidget,
        }

    def clean_expiration_date(self):
        expirate = self.cleaned_data['expiration_date']
        must_expire_in_the_future(expirate)

        return expirate


class ItemForm(forms.ModelForm):

    class Meta:
        model = Item
        fields = (
            'name',
            'description',
            'standard',
            'ingredients',
        )

menu/views.py
from django.db.models import Q
from django.shortcuts import redirect, render, get_object_or_404
from django.utils import timezone

from menu import models
from menu import forms


def menu_list(request):
    menus = models.Menu.objects.prefetch_related('items').filter(
        Q(expiration_date__gte=timezone.now().date()) |
        Q(expiration_date__isnull=True)
    ).order_by('-expiration_date')
    return render(request, 'menu/list_all_current_menus.html', {'menus': menus})


def menu_detail(request, pk):
    menu = get_object_or_404(models.Menu.objects.prefetch_related('items'), pk=pk)
    return render(request, 'menu/menu_detail.html', {'menu': menu})


def item_detail(request, pk):
    item = get_object_or_404(models.Item, pk=pk)
    return render(request, 'menu/detail_item.html', {'item': item})


def create_new_or_edit_menu(request, pk=None):
    """
     POST DATA:
        'expiration_date_day': ['int'],
        'expiration_date_month': ['int'],
        'expiration_date_year': ['int'],
        'items': ['int'],
        'season': [string]
    """
    if pk:
        menu = models.Menu.objects.get(pk=pk)
        form = forms.MenuForm(instance=menu)
        if request.method == 'POST':
            form = forms.MenuForm(data=request.POST, instance=menu)
            if form.is_valid():
                for item in menu.items.all():
                    item.menu_set.remove(menu)
                menu = form.save()
                return redirect(menu.get_absolute_url())
        return render(
            request,
            'menu/menu_edit.html',
            {'form': form, 'menu': menu})
    else:
        form = forms.MenuForm()
        if request.method == "POST":
            form = forms.MenuForm(request.POST)
            if form.is_valid():
                menu = form.save()
                for item in menu.items.all():
                    item.menu_set.add(menu)
                return redirect(menu.get_absolute_url())
        return render(
            request,
            'menu/menu_edit.html',
            {'form': form}
        )


def create_new_item(request):
    form = forms.ItemForm()
    if request.method == 'POST':
        form = forms.ItemForm(request.POST)
        if form.is_valid():
            item = form.save(commit=False)
            item.chef = request.user
            item.save()
            for ing in item.ingredients.all():
                ing.item_set.add(item)
            return redirect(item.get_absolute_url())
    return render(
        request=request,
        template_name='menu/item_new.html',
        context={'form': form}
    )


def edit_item(request, pk):
    item = models.Item.objects.get(pk=pk)
    form = forms.ItemForm(instance=item)
    if request.method == 'POST':
        form = forms.ItemForm(data=request.POST)
        if form.is_valid():
            for ing in item.ingredients.all():
                ing.ingredients.remove(item)
            item = form.save(commit=False)
            item.chef = request.user
            item.save()
            for ing in item.ingredients.all():
                ing.item_set.add(item)
            return redirect(item.get_absolute_url())
    return render(
        request=request,
        template_name='menu/item_new.html',
        context={
            'item': item,
            'form': form,
        }
    )

menu/templates/menu/detail_item.html
{% extends 'menu/layout.html' %}

{% block content %}
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
                <div class="post">
                    {% if user.is_authenticated %}
                        <a class="btn btn-default" href="{% url 'menu:item_edit' pk=item.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
                    {% endif %}
                    <h1>{{ item.name }}</h1>
                    <p><strong>Head Chef:</strong> {{ item.chef }}</p>
                    <p>{{ item.description }}</p>
                    <p><strong>Ingredients: </strong>{{ item.ingredients.all|join:", " }}</p>
                    {% if item.standard %}
                        <p><em>This item is available year-round.</em></p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

menu/templates/menu/item_list.html
{% extends 'menu/layout.html' %}

{% block content %}
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
                {% for item in items %}
                    <div>
                        <h1><a href="{% url 'item_detail' pk=item.pk %}">{{ item.title }}</a></h1>
                        <p>{{ item.description|linebreaks }}</p>
                        <p>published: {{ item.published_date }}</p>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

menu/templates/menu/item_new.html
{% extends 'menu/layout.html' %}

{% block content %}
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
                {% if item %}
                    <h1>Change this items ingredients</h1>
                {% else %}
                    <h1>Create New Item, Chef!</h1>
                {% endif %}
                <form method="POST" class="menu-form">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="save btn btn-default">Save</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

menu/templates/menu/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Soda Fountain</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    </head>
    <body>
        <div class="page-header">
            {% if user.is_authenticated %}
                <a href="{% url 'menu:menu_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span> Menu</a>
                <br>
                <a href="{% url 'menu:new_item' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span> Item</a>
            {% endif %}
            <h1><a href="/">Soda Fountain</a></h1>
        </div>
        {% block content %}
        {% endblock content %}
    </body>
</html>

menu/templates/menu/list_all_current_menus.html
{% extends 'menu/layout.html' %}

{% load menu_extras %}

{% block content %}
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
                <div class="post">
                    {% for menu in menus %}
                        <h1>
                            {% if user.is_authenticated %}
                                <a class="btn btn-default" href="{% url 'menu:menu_edit' pk=menu.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
                            {% endif %}
                            <a href="{% url 'menu:menu_detail' pk=menu.pk %}">{{ menu.season }}</a>
                        </h1>
                        <p>{{ menu.items.all|join_prefetched }}</p>
                        {% if menu.expiration_date %}
                            <div class="date">
                                Expires on: {{ menu.expiration_date }}
                            </div>
                        {% else %}
                            <p>This Menu is available year round</p>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

menu/templates/menu/menu_detail.html
{% extends 'menu/layout.html' %}

{% block content %}
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
                <div class="post">
                    <h1>
                        {% if user.is_authenticated %}
                            <a class="btn btn-default" href="{% url 'menu:menu_edit' pk=menu.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
                        {% endif %}
                        {{ menu.season }}
                    </h1>
                    <h2>On the menu this season:</h2>
                    <ul>
                        {% for item in menu.items.all %}
                            <li><a href="{% url 'menu:item_detail' pk=item.pk %}">{{ item }}</a></li>
                        {% endfor %}
                    </ul>
                    {% if menu.expiration_date %}
                        <div class="date">
                            Menu expires on {{ menu.expiration_date|date:"F j, Y" }}
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

menu/templates/menu/menu_edit.html
{% extends 'menu/layout.html' %}

{% block content %}
    <div class="content container">
        <div class="row">
            <div class="col-md-8">
                {% if menu %}
                    <h1>Edit Menu</h1>
                {% else %}
                    <h1>Create New Menu</h1>
                {% endif %}
                <form method="POST" class="menu-form">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="save btn btn-default">Save</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}